config/routes.rb
Pocketpharma::Application.routes.draw do

  root 'static_pages#home'
  
  resources :users do
    member do
      get    'edit_ds_chain'
      post   'update_ds_chain'
      post   'new_drugstore'
      delete 'delete_drugstore'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :rls_files do
    member do
      post 'treat'
    end
  end

  match '/get_progress/:id', to: 'delayed_jobs#get_progress', via: 'get'

  resources :drugstore_chains, only: [:index, :show]

  resources :drugstores, only: [:index, :show, :edit, :update] do
    member do
      post    'insert_ds_file'
      delete  'delete_ds_file'
    end
  end

  resources :rls_products, only: [:index]

  match '/signup',          to: 'users#new',                  via: 'get'
  match '/signin',          to: 'sessions#new',               via: 'get'
  match '/signout',         to: 'sessions#destroy',           via: 'delete'

  match '/manage',          to: 'static_pages#manage',        via: 'get'

  

  

end

app/models/drugstore.rb
class Drugstore < ActiveRecord::Base
	belongs_to :drugstore_chain
	belongs_to :user, foreign_key: "drugstore_chain_id", 
										primary_key: "drugstore_chain_id"
	has_many :ds_files, dependent: :destroy
	has_many :product_prices, dependent: :destroy

	validates :name, presence: true
end

app/controllers/drugstores_controller.rb
class DrugstoresController < ApplicationController

	before_filter :admin_check, 		only: 	[:index]
	before_filter :signed_in_check, except: [:index]
	before_filter :get_drugstore, 	only: 	[:show, :update, :insert_ds_file, :delete_ds_file]

  def index
  	@drugstores = Drugstore.all
  end

  def show
		@ds_files = @drugstore.ds_files
		@ds_file 	= DsFile.new
  end

  def update
  	@drugstore.update_attributes(drugstore_params)
  	redirect_to @drugstore
  end

  def insert_ds_file
  	@ds_file = @drugstore.ds_files.create(ds_file_params)
  end

  def delete_ds_file
  	DsFile.find(params[:ds_file][:id]).destroy
  	redirect_to @drugstore
  end

  private

  	def get_drugstore
  		@drugstore = Drugstore.find(params[:id])
  		@user = @drugstore.user
  		redirect_to current_user unless current_user.admin? || current_user == @user
  	end

  	def drugstore_params
  		params.require(:drugstore).permit(:name, :address, :working_hours, :phone)
  	end

  	def ds_file_params
  		params.require(:ds_file).permit(:file)
  	end

end

app/helpers/drugstores_helper.rb
module DrugstoresHelper
end

app/views/drugstores/_drugstore_form.html.erb
<%= form_for @drugstore, html: { role: "form" } do |f| %>

	<%= render 'shared/drugstore_form_fields', object: f %>

	<%= f.submit "Изменить", class: "btn btn-primary center-block" %>
	
<% end %>

app/views/drugstores/_ds_file_row.html.erb
<tr>
	<td><%= ds_file.file.url.split('/').last %></td>
	<td><%= number_to_human_size ds_file.file.size %></td>
	<td><%= ds_file.created_at %></td>
	<td>
		<%= form_for ds_file, url: delete_ds_file_drugstore_path(@drugstore), method: :delete do |f| %>
			<%= f.hidden_field :id %>
			<%= f.submit "Удалить", class: "btn btn-xs btn-danger", confirm: "Вы уверены, что хотите удалить этот файл?" %>
		<% end %>
	</td>
</tr>

app/views/drugstores/edit.html.erb
<h1>Drugstores#edit</h1>
<p>Find me in app/views/drugstores/edit.html.erb</p>

app/views/drugstores/index.html.erb
<h1>Drugstores#index</h1>
<p>Find me in app/views/drugstores/index.html.erb</p>

app/views/drugstores/insert_ds_file.js.erb
<% if @ds_file.new_record? %>
  alert('Failed');
<% else %>
  $('#file_table').append("<%=j render partial: 'ds_file_row', locals: { ds_file: @ds_file } %>");
<% end %>

app/views/drugstores/show.html.erb
<div class="row">
	
	<div class="col-lg-5 col-md-6 col-sm-6">
		<div class="well well-lg">

			<dl class="dl-horizontal">

				<dt>Нзвание</dt>
				<dd><%= @drugstore.name %></dd>

				<dt>Адрес</dt>
				<dd><%= @drugstore.address %></dd>

				<dt>Режим работы</dt>
				<dd><%= @drugstore.working_hours %></dd>

				<dt>Основной телефон</dt>
				<dd><%= @drugstore.phone %></dd>

			</dl>

		<%= button_to "Вернуться к списку аптек", @user, class: "btn btn-sm btn-primary center-block", method: :get %>

		</div>
	
	
	</div>

	<div class="col-lg-4 col-lg-offset-3 col-md-5 col-md-offset-1 col-sm-6">
		<div class="well">
			<%= render 'drugstore_form' %>
		</div>
	</div>

</div>

<div class="well">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6">
			<%= form_for @ds_file, url: insert_ds_file_drugstore_path(@drugstore), html: { class: "form-inline",role: "form" }  do |f| %>

				<div class="form-group">
				  <%= f.label :file, "Выберите файлы для загрузки: " %>
				  <%= f.file_field :file %>
				</div>
				
			<% end %>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-6" id="progress-bar">
		</div>
	</div>
</div>

<div class="table-responsive">
	<table class="table table-hover table-condensed" id="file_table">
		<tr>
			<th>Имя файла</th>
			<th>Размер</th>
			<th>Дата загрузки</th>
			<th>Удаление</th>
		</tr>

		<%= render partial: 'ds_file_row', collection: @ds_files, as: :ds_file %>
		
	</table>
</div>

<script id="template-upload" type="text/x-tmpl"><div class="progress"><div class="progress-bar" style="width: 0%"></div></div></script>