config/routes.rb
Pocketpharma::Application.routes.draw do

  root 'static_pages#home'
  
  resources :users do
    member do
      get    'edit_ds_chain'
      post   'update_ds_chain'
      post   'new_drugstore'
      delete 'delete_drugstore'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :rls_files do
    member do
      post 'treat'
    end
  end

  match '/get_progress/:id', to: 'delayed_jobs#get_progress', via: 'get'

  resources :drugstore_chains, only: [:index, :show]

  resources :drugstores, only: [:index, :show, :edit, :update] do
    member do
      post    'insert_ds_file'
      delete  'delete_ds_file'
    end
  end

  resources :rls_products, only: [:index]

  match '/signup',          to: 'users#new',                  via: 'get'
  match '/signin',          to: 'sessions#new',               via: 'get'
  match '/signout',         to: 'sessions#destroy',           via: 'delete'

  match '/manage',          to: 'static_pages#manage',        via: 'get'

  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	before_filter :admin_check, only: [:manage]

  def home
  	redirect_to current_user unless current_user.nil?
  end

  def manage
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">

	<h1 class="text-center">PocketPharma</h1>
	<h3 class="text-center">Поиск и бронирование лекарств в Москве</h2>

	<%= button_to "Поиск", root_path, class: "btn btn-large btn-primary center-block", method: :get %>
</div>

app/views/static_pages/manage.html.erb
<div class="row">
	<div class="col-md-6">

		<div class="row">
			<h3><%= link_to "Загрузка данных из РЛС", rls_files_path %></h3>
		</div>

		<div class="row">
			<h3>Нормализация базы РЛС</h3>
			<%= form_tag 'rls_normalize_path', class: "form-inline" do %>
			  <%= submit_tag "Выполнить" %>
			<% end %>

			<%= link_to "Эталонная база данных продуктов", 'products_path' %>
		</div>
		
		<div class="row">
			<h3>Загрузка данных из аптек</h3>
			<%= form_tag 'medlux_import_path', class: "form-inline center-block" do %> 
				
				<%= label_tag :from, "С" %>
				<%= number_field_tag :from %> 
				
				<%= label_tag :to, "По" %>
				<%= number_field_tag :to %>

				<%= check_box_tag :db, 'yes', true %>
				<%= label_tag :db, "БД" %>

				<%= submit_tag "Загрузить" %>
			<% end %>

			<%= link_to "Список аптек", 'drugstores_path' %>
		</div>

		<div class="row">
			<h3>Обновление аптечного ассортимента</h3>
			<%= form_tag 'dsp_update_path', class: "form-inline" do %>
				<%= check_box_tag :new, 'yes', true %> 
				<%= label_tag :new, "Поиск новых продуктов" %>
				<br>
				<%= check_box_tag :rel, 'yes', true %>
				<%= label_tag :rel, "Обновление связей" %>
				<br>
				<%= check_box_tag :avg, 'yes', true %>
				<%= label_tag :avg, "Обновление средней цены" %>
				<br>
			  <%= submit_tag "Выполнить" %>
			<% end %>

			<%= link_to "Список товаров аптечного ассортимента", 'ds_products_path' %>
		</div>

		<div class="row">
			<h3>Запуск сопоставления</h3>
			<%= form_tag 'fill_score_path', class: "form-inline" do %>
				<%= label_tag :count, "Количество" %>
				<%= number_field_tag :count %> 
				
				<%= label_tag :delay, "Через" %>
				<%= number_field_tag :delay %>
				<span>мин.</span>
				<br>
			  <%= submit_tag "Выполнить" %>
			<% end %>
		</div>

	</div>
</div>