config/routes.rb
Pocketpharma::Application.routes.draw do

  root 'static_pages#home'
  
  resources :users do
    member do
      get    'edit_ds_chain'
      post   'update_ds_chain'
      post   'new_drugstore'
      delete 'delete_drugstore'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :rls_files do
    member do
      post 'treat'
    end
  end

  match '/get_progress/:id', to: 'delayed_jobs#get_progress', via: 'get'

  resources :drugstore_chains, only: [:index, :show]

  resources :drugstores, only: [:index, :show, :edit, :update] do
    member do
      post    'insert_ds_file'
      delete  'delete_ds_file'
    end
  end

  resources :rls_products, only: [:index]

  match '/signup',          to: 'users#new',                  via: 'get'
  match '/signin',          to: 'sessions#new',               via: 'get'
  match '/signout',         to: 'sessions#destroy',           via: 'delete'

  match '/manage',          to: 'static_pages#manage',        via: 'get'

  

  

end

app/models/user.rb
class User < ActiveRecord::Base

	# Associations
	belongs_to :drugstore_chain

	# Authentication mechanism enabled
	has_secure_password

	# Validation section
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	
	validates :name, 	presence: true, 
										length: { maximum: 50 }

	validates :email, presence: true,
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }

	validates :password             , length: { minimum: 6 }, :if => :validate_password?
	validates :password_confirmation, length: { minimum: 6 }, :if => :validate_password?

	# Pre-branche invokes
	before_save { email.downcase! }
	before_create :create_remember_token

	# Ignore password when it doesn't matter
	def validate_password?
	  password.present? || password_confirmation.present?
	end

	# Optimal select
	def User.user_list
		joins("left outer join drugstore_chains on drugstore_chain_id = drugstore_chains.id").select("users.*, drugstore_chains.name as dsc_name, drugstore_chains.phone as dsc_phone")
	end

	# Security functions
	def User.new_remember_token
		SecureRandom.urlsafe_base64	
	end

	# Security functions
	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		# Security functions
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_check, 	except: [:new, :create]
	before_filter :admin_check, 			only: 	[:delete_drugstore]
	before_filter :get_user, 					except: [:index, :new, :create]
	before_filter :get_ds_chain, 			only: 	[:show, :edit_ds_chain, :new_drugstore]

	# User list
	def index
		redirect_to current_user unless current_user.admin?
		@users = User.user_list
	end

	# User Profile
	def show
		@drugstores = @ds_chain.drugstores
		@drugstore = Drugstore.new
	end

	# Singup from
	def new	
		@user = User.new
	end

	# Create new user
	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Добро пожаловать в сервис PocketPharma"
			redirect_to @user
		else
			render 'new'
		end
	end

	# Edit user profile
	def edit
	end

	# Update user profile
	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Данные успешно обновлены"
			redirect_to @user			
		else
			render 'edit'
		end
	end

	def edit_ds_chain	
	end

	# Create or edit new dugstore chain
	def update_ds_chain
		if @user.drugstore_chain
			@user.drugstore_chain.update_attributes(chain_params)
		else
			@user.create_drugstore_chain(chain_params)
			@user.save
		end

		flash[:success] = "Данные успешно обновлены"
		redirect_to @user
	end

	# New Drugstore
	def new_drugstore
		if @user.drugstore_chain.nil?
			flash[:danger] = "Укажите данные об аптечной сети"
		else
			@ds_chain.drugstores.create(drugstore_params)
		end
	
		redirect_to @user
	end

	# Delete Exising Drugstore
	def delete_drugstore
		Drugstore.find(params[:drugstore][:id]).destroy
  	redirect_to @user
	end

	private

		def get_user
			@user = current_user.admin? ? User.find(params[:id]) : current_user
		end

		def get_ds_chain
			@ds_chain = @user.drugstore_chain || DrugstoreChain.new
		end

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def chain_params
			params.require(:drugstore_chain).permit(:name, :phone, :description)
		end

		def drugstore_params
			params.require(:drugstore).permit(:name, :address, :working_hours, :phone)
		end
		
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_drugstore_chain_form.html.erb
<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">

	<%= form_for @ds_chain, url: update_ds_chain_user_path(@user), method: :post, html: { role: "form" } do |f| %>

		<div class="form-group">
			<%= f.label :name, "Название", class: "sr-only" %>
			<%= f.text_field :name, class: "form-control", placeholder: "Название аптечной сети" %>
		</div>

		<div class="form-group">
			<%= f.label :phone, "Телефон", class: "sr-only" %>
			<%= f.telephone_field :phone, class: "form-control", placeholder: "Основной телефон" %>
		</div>
		
		<div class="form-group">
			<%= f.label :description, "Описание", class: "sr-only" %>
			<%= f.text_area :description, class: "form-control", placeholder: "Описание" %>
		</div>

		<%= f.submit "Сохранить", class: "btn btn-primary center-block" %>

	<% end %>

</div>

app/views/users/_drugstore_form.html.erb
<%= form_for @drugstore, url: new_drugstore_user_path(@user), method: :post, html: { role: "form" } do |f| %>

	<%= render 'shared/drugstore_form_fields', object: f %>

	<%= f.submit "Добавить", class: "btn btn-primary center-block" %>
	
<% end %>

app/views/users/_user_form.html.erb
<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">

	<%= form_for @user, html: { role: "form" } do |f| %>

		<div class="form-group">
			<%= f.label :name, "Имя", class: "sr-only" %>
			<%= f.text_field :name, class: "form-control", placeholder: "Введите ваше имя" %>
		</div>
		
		<div class="form-group">
			<%= f.label :email, "Email", class: "sr-only" %>
			<%= f.email_field :email, class: "form-control", placeholder: "Email" %>
		</div>

		<div class="form-group">
			<%= f.label :password, "Пароль", class: "sr-only" %>
			<%= f.password_field :password, class: "form-control", placeholder: "Пароль" %>
		</div>

		<div class="form-group">
			<%= f.label :password_confirmation, "Повторите пароль", class: "sr-only" %>
				<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Повторить пароль" %>
		</div>

		<%= f.submit "Создать", class: "btn btn-primary center-block" %>

		<%= render 'shared/error_messages', object: f.object %>
		
	<% end %>

</div>

app/views/users/edit.html.erb
<h1 class="text-center">Параметры пользователя</h1>

<div class="row">
	
		<%= render 'user_form' %>
		
</div>

app/views/users/edit_ds_chain.html.erb
<h1 class="text-center">Данные аптечной сети</h1>

<div class="row">
		
		<%= render 'drugstore_chain_form' %>
	
</div>

app/views/users/index.html.erb
<h1>Пользователи</h1>

<div class="table-responsive">
	<table class="table table-condensed table-hover" id="file_lis">
		<tr>
			<th>Админ</th>
			<th>Имя</th>
			<th>Email</th>
			<th>Аптечная сеть</th>
			<th>Основной телефон</th>
		</tr>
		
		<% @users.each do |user| %>
			<tr>
				<td>
					<% if user.admin? %>
						<span class="glyphicon glyphicon-ok"></span>
					<% end %>
				</td>
				<td><%= link_to user.name, user %></td>
				<td><%= user.email %></td>
				<td><%= user.dsc_name %></td>
				<td><%= user.dsc_phone %></td>
			</tr>
		<% end %>

	</table>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Новый пользователь</h1>

<div class="row">

		<%= render 'user_form' %>

</div>

app/views/users/show.html.erb
<div class="row">

	<div class="col-lg-5 col-md-5 col-sm-6">
		<div class="well well-lg">
			<dl class="dl-horizontal">
				<dt>Имя</dt>
				<dd><%= @user.name %></dd>
				<dt>Email</dt>
				<dd><%= @user.email %></dd>

				<% unless @user.admin? %>
					<dt>Аптечная сеть</dt>
					<dd><%= @ds_chain.name %></dd>
					<dt>Основной телефон</dt>
					<dd><%= @ds_chain.phone %></dd>
					<dt>Описание</dt>
					<dd><%= @ds_chain.description %></dd>
				<% end %>
			</dl>

			<% unless @user.admin? %>
				<%= button_to "Обновить данные аптечной сети", edit_ds_chain_user_path(@user), class: "btn btn-sm btn-primary center-block", method: :get %>
			<% end %>

		</div>
	</div>

	<div class="col-lg-4 col-lg-offset-3 col-md-5 col-md-offset-2 col-sm-6">

		<% unless @user.admin? %>
			<div class="well">
				<%= render 'drugstore_form' %>
			</div>
		<% end %>
	</div>
</div>

<div class="table-responsive">
	<table class="table table-hover table-condensed">
		<tr>
			<th>Имя</th>
			<th>Адрес</th>
			<th>Режим работы</th>
			<th>Телефон</th>
			<% if current_user.admin? %>
				<th>Удалить</th>
			<% end %>
		</tr>
		
		<% @drugstores.each do |ds| %>
			<tr>
				<td><%= link_to ds.name, ds %></td>
				<td><%= ds.address %></td>
				<td><%= ds.working_hours %></td>
				<td><%= ds.phone %></td>
				<% if current_user.admin? %>
					<td>
						<%= form_for(ds, url: delete_drugstore_user_path(@user), method: :delete) do |f| %>
							<%= f.hidden_field :id %>
							<%= f.submit "Удалить", class: "btn btn-xs btn-danger", confirm: 'Вы уверены, что хотите удалить эту запись?' %>
						<% end %>
					</td>
				<% end %>
			</tr>
		<% end %>

	</table>
</div>