config/routes.rb
Pocketpharma::Application.routes.draw do

  root 'static_pages#home'
  
  resources :users do
    member do
      get    'edit_ds_chain'
      post   'update_ds_chain'
      post   'new_drugstore'
      delete 'delete_drugstore'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :rls_files do
    member do
      post 'treat'
    end
  end

  match '/get_progress/:id', to: 'delayed_jobs#get_progress', via: 'get'

  resources :drugstore_chains, only: [:index, :show]

  resources :drugstores, only: [:index, :show, :edit, :update] do
    member do
      post    'insert_ds_file'
      delete  'delete_ds_file'
    end
  end

  resources :rls_products, only: [:index]

  match '/signup',          to: 'users#new',                  via: 'get'
  match '/signin',          to: 'sessions#new',               via: 'get'
  match '/signout',         to: 'sessions#destroy',           via: 'delete'

  match '/manage',          to: 'static_pages#manage',        via: 'get'

  

  

end

app/models/drugstore.rb
class Drugstore < ActiveRecord::Base
	belongs_to :drugstore_chain
	belongs_to :user, foreign_key: "drugstore_chain_id", 
										primary_key: "drugstore_chain_id"
	has_many :ds_files, dependent: :destroy
	has_many :product_prices, dependent: :destroy

	validates :name, presence: true
end

app/models/drugstore_chain.rb
class DrugstoreChain < ActiveRecord::Base
	has_many :drugstores
	has_one :user
end

app/models/ds_file.rb
class DsFile < ActiveRecord::Base

	belongs_to :drugstore

	mount_uploader :file, DrugstoreFileUploader

end

app/models/ds_product.rb
class DsProduct < ActiveRecord::Base
end

app/models/product_price.rb
class ProductPrice < ActiveRecord::Base
end

app/models/rls_file.rb
class RlsFile < ActiveRecord::Base

	mount_uploader :rls_file, RlsFileUploader

	belongs_to :user

	before_create :set_default_name
	before_create :set_default_size
	
	def RlsFile.files_list
		includes(:user)
	end

	def user_name
		user.name if user		
	end

	private

		def set_default_name
		  self.name ||= File.basename(rls_file.filename, '.*') if rls_file
		end

		def set_default_size
		  self.size ||= rls_file.size() if rls_file
		end

end

app/models/rls_product.rb
class RlsProduct < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	# Associations
	belongs_to :drugstore_chain

	# Authentication mechanism enabled
	has_secure_password

	# Validation section
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	
	validates :name, 	presence: true, 
										length: { maximum: 50 }

	validates :email, presence: true,
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }

	validates :password             , length: { minimum: 6 }, :if => :validate_password?
	validates :password_confirmation, length: { minimum: 6 }, :if => :validate_password?

	# Pre-branche invokes
	before_save { email.downcase! }
	before_create :create_remember_token

	# Ignore password when it doesn't matter
	def validate_password?
	  password.present? || password_confirmation.present?
	end

	# Optimal select
	def User.user_list
		joins("left outer join drugstore_chains on drugstore_chain_id = drugstore_chains.id").select("users.*, drugstore_chains.name as dsc_name, drugstore_chains.phone as dsc_phone")
	end

	# Security functions
	def User.new_remember_token
		SecureRandom.urlsafe_base64	
	end

	# Security functions
	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		# Security functions
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

end

app/controllers/rls_files_controller.rb
class RlsFilesController < ApplicationController

	before_filter :admin_check
	before_filter :get_rls_file, only: [:destroy, :treat]

	def index
		@rls_files = RlsFile.files_list
		@rls_file = RlsFile.new(user_id: current_user.id)
	end

	def create
		@rls_file = RlsFile.create(rls_file_params)
	end

	def destroy
		@rls_file.destroy
		redirect_to rls_files_path
	end

	def treat
		@job = Delayed::Job.enqueue(RlsFileWorker.new(@rls_file.rls_file.url()))
	end


	
	private

		def get_rls_file
			@rls_file = RlsFile.find(params[:id])
		end

		def rls_file_params
			params.require(:rls_file).permit(:user_id, :rls_file)
		end
		
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:email].downcase)
		if user && user.authenticate(params[:password])
			sign_in user
			if user.admin?
				redirect_to manage_path
			else
				redirect_to user
			end
		else
			flash.now[:error] = "Некорректная комбинация имени пользователя и пароля"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_check, 	except: [:new, :create]
	before_filter :admin_check, 			only: 	[:delete_drugstore]
	before_filter :get_user, 					except: [:index, :new, :create]
	before_filter :get_ds_chain, 			only: 	[:show, :edit_ds_chain, :new_drugstore]

	# User list
	def index
		redirect_to current_user unless current_user.admin?
		@users = User.user_list
	end

	# User Profile
	def show
		@drugstores = @ds_chain.drugstores
		@drugstore = Drugstore.new
	end

	# Singup from
	def new	
		@user = User.new
	end

	# Create new user
	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Добро пожаловать в сервис PocketPharma"
			redirect_to @user
		else
			render 'new'
		end
	end

	# Edit user profile
	def edit
	end

	# Update user profile
	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Данные успешно обновлены"
			redirect_to @user			
		else
			render 'edit'
		end
	end

	def edit_ds_chain	
	end

	# Create or edit new dugstore chain
	def update_ds_chain
		if @user.drugstore_chain
			@user.drugstore_chain.update_attributes(chain_params)
		else
			@user.create_drugstore_chain(chain_params)
			@user.save
		end

		flash[:success] = "Данные успешно обновлены"
		redirect_to @user
	end

	# New Drugstore
	def new_drugstore
		if @user.drugstore_chain.nil?
			flash[:danger] = "Укажите данные об аптечной сети"
		else
			@ds_chain.drugstores.create(drugstore_params)
		end
	
		redirect_to @user
	end

	# Delete Exising Drugstore
	def delete_drugstore
		Drugstore.find(params[:drugstore][:id]).destroy
  	redirect_to @user
	end

	private

		def get_user
			@user = current_user.admin? ? User.find(params[:id]) : current_user
		end

		def get_ds_chain
			@ds_chain = @user.drugstore_chain || DrugstoreChain.new
		end

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def chain_params
			params.require(:drugstore_chain).permit(:name, :phone, :description)
		end

		def drugstore_params
			params.require(:drugstore).permit(:name, :address, :working_hours, :phone)
		end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delayed_jobs_helper.rb
module DelayedJobsHelper
end

app/helpers/drugstore_chains_helper.rb
module DrugstoreChainsHelper
end

app/helpers/drugstores_helper.rb
module DrugstoresHelper
end

app/helpers/rls_files_helper.rb
module RlsFilesHelper
end

app/helpers/rls_products_helper.rb
module RlsProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
		
	def signed_in?
		!current_user.nil?
	end

	def current_user?(user)
		user == current
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by(remember_token: User.encrypt(cookies[:remember_token]))
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
	<div class="container">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	    <%= link_to "PocketPharma", root_path, class: "navbar-brand", id: "logo" %>
	  </div>

	  <div class="collapse navbar-collapse" id="navbar-collapse-1">
	    <ul class="nav navbar-nav navbar-right">
	    	
				<% if signed_in? %>

		      <% if current_user.admin? %>
		      	<li><%= link_to "Администрирование", manage_path %></li>
		      	<li><%= link_to "Пользователи", users_path %></li>
		      	<li><%= link_to "Атечные сети", drugstore_chains_path %></li>
		      <% end %>
		    
		      <li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
		        <ul class="dropdown-menu">
		          <li><%= link_to "Параметры пользователя", edit_user_path(current_user) %></li>
		          <li class="divider"></li>
		          <li><%= link_to "Выход", signout_path, method: :delete %></li>
		        </ul>
		      </li>
				
				<% else %>
		    
		      <li><%= link_to "Вход в систему", signin_path %></li>
		      <li><%= link_to "Регистрация", signup_path %></li>
		    
		    <% end %>

	    </ul>
	  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pocketpharma</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	 <%= render 'layouts/header' %>

	<div class="container">
    
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

		<%= yield %>

	</div>

</body>
</html>

app/views/shared/_drugstore_form_fields.html.erb
<div class="form-group">
	<%= object.label :name, "Название торговой точки", class: "sr-only" %>
	<%= object.text_field :name, class: "form-control", placeholder: "Название торговой точки" %>
</div>

<div class="form-group">
	<%= object.label :address, "Адрес", class: "sr-only" %>
	<%= object.text_field :address, class: "form-control", placeholder: "Адрес" %>
</div>

<div class="form-group">
	<%= object.label :working_hours, "Режим работы", class: "sr-only" %>
	<%= object.text_field :working_hours, class: "form-control", placeholder: "Режим работы" %>
</div>

<div class="form-group">
	<%= object.label :phone, "Телефон", class: "sr-only" %>
	<%= object.telephone_field :phone, class: "form-control", placeholder: "Телефон" %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

<div id="error_explanation">
	
	<div class="alert alert-error">
		При заполнении формы возникли ошибки
	</div>

	<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
</div>

<% end %>

app/views/shared/_rls_admin_nav.html.erb
<ul class="nav nav-tabs">

  <%= content_tag :li, class: "#{menu_item[:file]}" do %>
		<%= link_to 'Файлы', rls_files_path %>
  <% end %>

  <%= content_tag :li, class: "#{menu_item[:rls]}" do %>
		<%= link_to 'РЛС', rls_products_path %>
  <% end %>

  <%= content_tag :li do %>
		<%= link_to 'Эталонная база', '#' %>
  <% end %>

</ul>